# Puerto donde correrá tu backend
server.port=8080

# Conexión a PostgreSQL (Asegúrate de poner tu contraseña real)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate: Crea las tablas automáticamente en Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Apagamos temporalmente la seguridad para poder probar sin que nos pida login
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration